name: Containerize and Deploy

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build and push web
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./web
        file: ./web/Dockerfile
        push: true
        tags: ghcr.io/${{github.repository_owner}}/g-yachts-web:${{github.sha}}

    - name: Build and push API
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./api
        file: ./api/Dockerfile
        push: true
        tags: ghcr.io/${{github.repository_owner}}/g-yachts-api:${{github.sha}}
        
  Deploy:
    runs-on: ubuntu-latest
    needs: Build

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SERVER_IP}}
        username: ${{secrets.SERVER_USER}}
        password: ${{secrets.SERVER_PASSWORD}}
        script: |
          sudo mkdir -p /var/www/docker
          cd /var/www/docker
          sudo rm -rf .env
          sudo docker rmi $(sudo docker images)
          echo "GITHUB_SHA=${{ github.sha }}" > .env
          echo "GITHUB_OWNER=${{github.repository_owner}}" >> .env
          echo "CURRENCY_API_KEY=${{secrets.CURRENCY_API}}" >> .env
          echo "MONGO_URI=mongodb://${{secrets.SERVER_IP}}:27017" >> .env
          echo "MONGO_USER=${{secrets.MONGO_USER}}" >> .env
          echo "MONGO_PASS=${{secrets.MONGO_PASS}}" >> .env
          echo "SUBNET_IP=${{secrets.SUBNET_WEB_IP}}" >> .env

    - name: Transfer Compose
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.SERVER_IP}}
        username: ${{secrets.SERVER_USER}}
        password: ${{secrets.SERVER_PASSWORD}}
        source: ./docker-compose.yml
        target: /var/www/docker

    - name: Start Services
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SERVER_IP}}
        username: ${{secrets.SERVER_USER}}
        password: ${{secrets.SERVER_PASSWORD}}
        script: |
          cd /var/www/docker
          sudo docker-compose pull
          sudo docker-compose down
          sudo docker-compose up -d
